# Generated by Django 5.1.6 on 2025-02-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_car_brand_alter_car_model_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('supercar', 'Суперкари'), ('classic', 'Класичні'), ('electric', 'Електро'), ('race', 'Гоночні')], default='supercar', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
